In [1]:
import sys
import os

In [ ]:
sys.path.insert(0, os.path.abspath('./SIRT6_db/utils/'))

In [3]:
from python_client import SIRT6db

## Access database

In [20]:
db = SIRT6db(db_path='./SIRT6_db')

Check the version

In [21]:
db.version()

'0.0.1'

Check available species

In [22]:
db.available_species()

['Homo sapiens',
 'Macaca fascicularis',
 'Mus musculus',
 'Rattus norvegicus',
 'Sus scrofa']

Check available experiments

In [23]:
db.list_experiments()

,organism,genotype,sample_ids,counts
0,Homo sapiens,SIRT6-Het,"[SRX3103125, SRX3103126, SRX3103127, SRX310312...",6
1,Homo sapiens,SIRT6-KO,"[SRX827482, SRX827483, SRX827486, SRX827487, S...",21
2,Homo sapiens,SIRT6-OE,"[SRX17247281, SRX17247283, SRX17247289, SRX172...",6
3,Homo sapiens,SIRT6-OE/K3Q,"[SRX17247278, SRX17247282, SRX17247285, SRX172...",6
4,Homo sapiens,SIRT6-OE/K3R,"[SRX17247280, SRX17247287, SRX17247291, SRX172...",6
5,Homo sapiens,WT,"[SRX827480, SRX827481, SRX827484, SRX827485, S...",27
6,Mus musculus,SIRT6-KO,"[SRX22217578, SRX22217579, SRX22217580, SRX208...",63
7,Mus musculus,SIRT6-OE,"[SRX17966093, SRX17966094, SRX27428289, SRX274...",21
8,Mus musculus,WT,"[SRX22217575, SRX22217576, SRX22217577, SRX208...",91
9,Macaca fascicularis,SIRT6-KO,"[SRX3104138, SRX3104139, SRX3104140, SRX310414...",28
10,Macaca fascicularis,WT,"[SRX3104130, SRX3104131, SRX3104132, SRX310413...",36
11,Rattus norvegicus,SIRT6-KO,"[SRX25977004, SRX25977005, SRX25977006, SRX259...",4
12,Rattus norvegicus,WT,"[SRX25977000, SRX25977001, SRX25977002, SRX259...",4
13,Sus scrofa,SIRT6-KO,"[SRX9461174, SRX9461171]",2
14,Sus scrofa,WT,"[SRX9461172, SRX9461173]",2

Load example dataset

In [24]:
data = db.load_dataset(gse_id = "GSE213425", species = "homo_sapiens")

Loading dataset GSE213425 for homo_sapiens...
  -> Loaded expression matrix: (78899, 4)
  -> Loaded metadata for 4 samples.
  -> Loaded gene annotations for 78899 genes.

In [25]:
data.keys()

dict_keys(['expression', 'samples', 'genes'])

In [26]:
data.get("expression", "NA").head()

                 SRX17591686  SRX17591683  SRX17591684  SRX17591685
gene_id
ENSG00000000003     1066.999     1610.000      588.001      545.000
ENSG00000000005        0.000        0.000        0.000        0.000
ENSG00000000419      799.001      932.001     1081.999      897.001
ENSG00000000457      174.001      193.999      144.000       92.000
ENSG00000000460      163.001       58.999      133.000       47.000

In [27]:
data.get("samples", "NA")

,sample_id,organism,tissue,genotype,treatment,cell_type,sex,strain,age,condition
50,SRX17591686,Homo sapiens,Umbilical vein,WT,Control,endothelial cells,None,None,None,Control
51,SRX17591683,Homo sapiens,Umbilical vein,WT,Control,endothelial cells,None,None,None,Control
52,SRX17591684,Homo sapiens,Umbilical vein,SIRT6-KO,Control,endothelial cells,None,None,None,Control
53,SRX17591685,Homo sapiens,Umbilical vein,SIRT6-KO,Control,endothelial cells,None,None,None,Control

In [28]:
data.get("genes", "NA")

               gene_id        gene_name
0      ENSG00000000003           TSPAN6
1      ENSG00000000005             TNMD
2      ENSG00000000419             DPM1
3      ENSG00000000457            SCYL3
4      ENSG00000000460            FIRRM
...                ...              ...
78894  ENSG00000310589  ENSG00000310589
78895  ENSG00000310590  ENSG00000310590
78896  ENSG00000310591          OTP-AS1
78897  ENSG00000310592  ENSG00000310592
78898  ENSG00000310593  ENSG00000310593

[78899 rows x 2 columns]

Preprocess the data

In [29]:
filtered_data = db.filter_low_expressed_genes(data, min_counts = 5, min_samples_pct = 0.4, max_zeros_pct = 0.6)

--- Filtering Lowly Expressed Genes ---
Initial gene count: 78899
Genes passing filter: 17428
Genes removed: 61471

Now create an anndata object

In [30]:
adata = db.get_anndata_object(filtered_data)

In [31]:
adata.var

                       gene_name
gene_id
ENSG00000000003           TSPAN6
ENSG00000000419             DPM1
ENSG00000000457            SCYL3
ENSG00000000460            FIRRM
ENSG00000000938              FGR
...                          ...
ENSG00000310540        LINC02968
ENSG00000310560             PAXX
ENSG00000310576          FAM174C
ENSG00000310586  ENSG00000310586
ENSG00000310592  ENSG00000310592

[17428 rows x 1 columns]